name: Microsoft Sentinel Detections

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 00 * * *'


jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout branch
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
        path: Microsoft-Sentinel

    - name: checkout Azure Sentinel
      uses: actions/checkout@v3
      with:
        repository: Azure/Azure-Sentinel
        path: Azure-Sentinel

    - name: check repo content
      run: |
        ls -al

    - name: Convert Detection rules
      shell: pwsh
      run: |
        Write-Host "Function start"

        ./Microsoft-Sentinel/.script/ConvertFrom-YamlSentinelRule.ps1 `
          -SourcePath "./Azure-Sentinel/Detections" `
          -OutputFolder "./Microsoft-Sentinel/Detections" `
          -Verbose

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert Solution Rules
      shell: pwsh
      run: |
        Write-Host "Function start"

        $solutions = Get-ChildItem "./Azure-Sentinel/Solutions" | Where-Object { $(Test-Path "$($_.FullName)/Analytic Rules") -eq $true }

        foreach ($solution in $solutions) {
          ./.script/ConvertFrom-YamlSentinelRule.ps1 `
            -SourcePath "$($solution.FullName)/Analytic Rules/" `
            -OutputFolder "./Microsoft-Sentinel//Solutions/$($solution.Name)/Analytic Rules/" `
            -Verbose
        }


      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit files
      shell: pwsh
      run: |
        Write-Host "stage 1"

        # Switch to Microsoft-Sentinel folder
        cd "./Microsoft-Sentinel"

        # Test to see if there are any git changes that need to be commit
        if ($null -eq $(git update-index --refresh && git diff-index --quiet HEAD -- )) {
            Write-Host "No changes to commit"
        }
        else {
            Write-Host "Found changes that need to be updated"

            # Start commit and push changes
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update changes"
            git push
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
